import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:intl/intl.dart';

import '../../core/web/web_platform.dart' as web_platform;
import '../models/vital.dart';
import '../models/vital_report_request.dart';
import '../models/vital_statistics.dart';
import '../state/vitals_state.dart';

/// Opens a printable vital report summary in a new browser tab.
class VitalReportExport {
  VitalReportExport._();

  static void openInNewTab(VitalReportRequest request) {
    if (!kIsWeb) return;

    final fmt = DateFormat.yMMMd().add_jm();
    final note = _escape(request.responseNote ?? 'No clinical note attached.');
    final vitalNames = _escape(request.vitals.map((v) => v.label).join(', '));
    final statistics = _statisticsSections(request);
    final html =
        '''
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>$vitalNames Report</title>
<style>
body{font-family:system-ui,sans-serif;margin:2rem;color:#1a1a2e}
h1{font-size:1.4rem;margin-bottom:.25rem}
.meta{color:#555;font-size:.9rem;margin-bottom:1.5rem}
section{margin:1rem 0;padding:1rem;border:1px solid #e5e7eb;border-radius:8px}
table{width:100%;border-collapse:collapse;margin-top:.75rem;font-size:.86rem}
th,td{text-align:left;padding:.45rem;border-bottom:1px solid #e5e7eb}
th{color:#555;font-weight:600}.chart{width:100%;height:92px;margin-top:.75rem}
.empty{color:#666;font-size:.9rem}.trend{font-weight:600;color:#5146e5}
</style></head><body>
<h1>$vitalNames — Vital Report</h1>
<p class="meta">Requested ${fmt.format(request.createdAt)} · Status: ${request.status.name}</p>
<section><strong>Responded by</strong><br>${request.respondedBy ?? '—'}<br>
<small>${request.respondedAt != null ? fmt.format(request.respondedAt!) : ''}</small></section>
<section><strong>Clinical note</strong><p>$note</p></section>
$statistics
<p><small>Generated by mCare · ${fmt.format(DateTime.now())}</small></p>
</body></html>''';

    final dataUrl = 'data:text/html;charset=utf-8,${Uri.encodeComponent(html)}';
    web_platform.openWindow(dataUrl, '_blank');
  }

  static String _statisticsSections(VitalReportRequest request) {
    final sections = <String>[];
    for (final vital in request.vitals) {
      final readings = VitalsState.instance
          .forVital(vital)
          .where(
            (reading) =>
                !reading.recordedAt.isBefore(request.from) &&
                !reading.recordedAt.isAfter(
                  DateTime(
                    request.to.year,
                    request.to.month,
                    request.to.day,
                    23,
                    59,
                    59,
                  ),
                ),
          )
          .toList()
        ..sort((a, b) => a.recordedAt.compareTo(b.recordedAt));
      final stats = VitalStatistics.from(readings);

      if (readings.isEmpty) {
        sections.add(
          '<section><strong>${_escape(vital.label)}</strong>'
          '<p class="empty">No readings in the requested period.</p></section>',
        );
        continue;
      }

      String value(double? number) {
        if (number == null) return '—';
        final decimal =
            vital == VitalKey.temperature || vital == VitalKey.weight;
        return '${number.toStringAsFixed(decimal ? 1 : 0)} ${_escape(vital.unit)}';
      }

      sections.add(
        '<section><strong>${_escape(vital.label)}</strong>'
        '<div class="trend">${_escape(stats.trend.label)} trend</div>'
        '${_sparkline(readings, vital.accent.toARGB32())}'
        '<table><thead><tr><th>Readings</th><th>Average</th><th>Lowest</th>'
        '<th>Highest</th><th>In range</th></tr></thead><tbody><tr>'
        '<td>${stats.count}</td><td>${value(stats.average)}</td>'
        '<td>${value(stats.lowest)}</td><td>${value(stats.highest)}</td>'
        '<td>${stats.inRangePercent ?? 0}%</td></tr></tbody></table></section>',
      );
    }
    return sections.join();
  }

  static String _sparkline(List<VitalReading> readings, int colorValue) {
    if (readings.length < 2) return '';
    const width = 520.0;
    const height = 82.0;
    final values = readings.map((reading) => reading.value).toList();
    final low = values.reduce((a, b) => a < b ? a : b);
    final high = values.reduce((a, b) => a > b ? a : b);
    final span = high == low ? 1.0 : high - low;
    final points = <String>[];
    for (var i = 0; i < readings.length; i++) {
      final x = i / (readings.length - 1) * width;
      final y = height - ((readings[i].value - low) / span * (height - 12)) - 6;
      points.add('${x.toStringAsFixed(1)},${y.toStringAsFixed(1)}');
    }
    final rgb = colorValue & 0x00ffffff;
    final color = '#${rgb.toRadixString(16).padLeft(6, '0')}';
    return '<svg class="chart" viewBox="0 0 520 82" '
        'preserveAspectRatio="none" role="img" aria-label="Trend chart">'
        '<polyline fill="none" stroke="$color" stroke-width="3" '
        'stroke-linecap="round" stroke-linejoin="round" '
        'points="${points.join(' ')}"/></svg>';
  }

  static String _escape(String value) => value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}
