import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:intl/intl.dart';

import '../../core/web/web_platform.dart' as web_platform;
import '../models/vital_report_request.dart';

/// Opens a printable vital report summary in a new browser tab.
class VitalReportExport {
  VitalReportExport._();

  static void openInNewTab(VitalReportRequest request) {
    if (!kIsWeb) return;

    final fmt = DateFormat.yMMMd().add_jm();
    final note = request.responseNote ?? 'No clinical note attached.';
    final vitalNames = request.vitals.map((v) => v.label).join(', ');
    final html =
        '''
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>$vitalNames Report</title>
<style>
body{font-family:system-ui,sans-serif;margin:2rem;color:#1a1a2e}
h1{font-size:1.4rem;margin-bottom:.25rem}
.meta{color:#555;font-size:.9rem;margin-bottom:1.5rem}
section{margin:1rem 0;padding:1rem;border:1px solid #e5e7eb;border-radius:8px}
</style></head><body>
<h1>$vitalNames — Vital Report</h1>
<p class="meta">Requested ${fmt.format(request.createdAt)} · Status: ${request.status.name}</p>
<section><strong>Responded by</strong><br>${request.respondedBy ?? '—'}<br>
<small>${request.respondedAt != null ? fmt.format(request.respondedAt!) : ''}</small></section>
<section><strong>Clinical note</strong><p>$note</p></section>
<p><small>Generated by mCare · ${fmt.format(DateTime.now())}</small></p>
</body></html>''';

    final dataUrl = 'data:text/html;charset=utf-8,${Uri.encodeComponent(html)}';
    web_platform.openWindow(dataUrl, '_blank');
  }
}
