<?php

namespace App\Services;

/**
 * Renders a frozen report snapshot into a self-contained, printable page.
 *
 * `PatientReportService::issue()` assembles the report, freezes it into the
 * request's `snapshot` column and tells the patient it went out — but nothing
 * could ever render that snapshot back, so the one person whose record it is
 * could not read what had been disclosed about them. This turns the stored
 * array back into a document.
 *
 * HTML rather than PDF on purpose: the project has no PDF engine, and adding
 * one to render a table of label/value pairs buys nothing a print stylesheet
 * does not. Every browser prints this to PDF, and unlike a generated PDF it
 * stays readable to a screen reader.
 *
 * The markup is deliberately dependency-free — inline styles, no scripts, no
 * remote assets — so it renders identically saved to disk, mailed on, or
 * opened from a phone with no network.
 */
final class PatientReportRenderer
{
    /**
     * @param  array<string, mixed>  $snapshot  Output of PatientReportAssembler.
     */
    public function toHtml(array $snapshot, ?string $watermark = null): string
    {
        $title = $this->text($snapshot['title'] ?? 'Medical report');
        $body = $this->header($snapshot)
            .$this->provenance($snapshot)
            .$this->sections($snapshot['sections'] ?? []);

        $banner = $watermark === null ? '' : $this->banner($watermark);

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{$title}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 32px 20px; background: #F1F5F9; color: #0F172A;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
      "Helvetica Neue", Arial, sans-serif; line-height: 1.55;
  }
  .sheet {
    max-width: 820px; margin: 0 auto; background: #fff; border-radius: 14px;
    padding: 36px 40px; box-shadow: 0 1px 3px rgba(15,23,42,.12);
  }
  h1 { font-size: 24px; margin: 0 0 4px; }
  h2 {
    font-size: 15px; text-transform: uppercase; letter-spacing: .06em;
    color: #475569; margin: 32px 0 10px; padding-bottom: 6px;
    border-bottom: 1px solid #E2E8F0;
  }
  .eyebrow {
    text-transform: uppercase; letter-spacing: .08em; font-size: 11px;
    font-weight: 700; color: #6366F1; margin: 0 0 6px;
  }
  .muted { color: #64748B; font-size: 13px; margin: 0; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th, td {
    text-align: left; padding: 8px 10px; border-bottom: 1px solid #EEF2F7;
    vertical-align: top;
  }
  th { color: #475569; font-weight: 600; background: #F8FAFC; }
  .fields td:first-child { color: #475569; width: 38%; }
  .empty { color: #94A3B8; font-style: italic; font-size: 14px; margin: 6px 0; }
  .banner {
    background: #FEF2F2; border: 1px solid #FECACA; color: #991B1B;
    border-radius: 10px; padding: 12px 14px; margin: 0 0 20px;
    font-size: 14px; font-weight: 600;
  }
  .foot {
    margin-top: 32px; padding-top: 14px; border-top: 1px solid #E2E8F0;
    color: #94A3B8; font-size: 12px;
  }
  /* Printing is how this becomes a PDF, so the page must not carry the
     screen's grey backdrop or the card shadow onto paper. */
  @media print {
    body { background: #fff; padding: 0; }
    .sheet { box-shadow: none; border-radius: 0; padding: 0; max-width: none; }
    h2 { break-after: avoid; }
    tr { break-inside: avoid; }
  }
</style>
</head>
<body>
<div class="sheet">
{$banner}{$body}
<p class="foot">Generated by mCare from your medical record. If anything here
looks wrong, contact your care team — do not edit this document.</p>
</div>
</body>
</html>
HTML;
    }

    /** @param array<string, mixed> $s */
    private function header(array $s): string
    {
        $title = $this->text($s['title'] ?? 'Medical report');
        $name = $this->text($s['patient_name'] ?? '');
        $uid = $this->text($s['patient_unique_id'] ?? '');
        $subject = $uid === '' ? $name : $name.' · '.$uid;

        return '<p class="eyebrow">Medical report</p>'
            ."<h1>{$title}</h1>"
            ."<p class=\"muted\">{$subject}</p>";
    }

    /**
     * Who asked for this, why, who received it, and on what authority. A
     * disclosure the patient cannot trace back is not one they can challenge.
     *
     * @param  array<string, mixed>  $s
     */
    private function provenance(array $s): string
    {
        $consent = is_array($s['consent'] ?? null) ? $s['consent'] : [];
        $signature = is_array($s['signature'] ?? null) ? $s['signature'] : [];

        $rows = [
            'Purpose' => $s['purpose'] ?? null,
            'Released to' => $s['recipient'] ?? null,
            'Prepared by' => $s['prepared_by'] ?? null,
            'Generated' => $this->moment($s['generated_at'] ?? null),
            'Your consent' => ($consent['required'] ?? false)
                ? $this->consentLine($consent)
                : 'Not required for this report',
            'Clinician signature' => ($signature['required'] ?? false)
                ? $this->signatureLine($signature)
                : 'Not required for this report',
        ];

        return '<h2>About this report</h2>'.$this->fieldTable($rows);
    }

    /** @param array<string, mixed> $consent */
    private function consentLine(array $consent): string
    {
        $at = $this->moment($consent['granted_at'] ?? null);
        if ($at === null) {
            return 'Required — not yet given';
        }
        $method = $consent['method'] ?? null;

        return 'Given '.$at.($method ? ' (via '.$method.')' : '');
    }

    /** @param array<string, mixed> $signature */
    private function signatureLine(array $signature): string
    {
        $at = $this->moment($signature['signed_at'] ?? null);
        if ($at === null) {
            return 'Required — not yet signed';
        }
        $name = $signature['name'] ?? null;

        return ($name ? $name.' — ' : '').'signed '.$at;
    }

    /** @param array<int, mixed> $sections */
    private function sections(array $sections): string
    {
        $out = '';
        foreach ($sections as $block) {
            if (! is_array($block)) {
                continue;
            }
            $out .= '<h2>'.$this->text($block['title'] ?? 'Section').'</h2>';
            $out .= ($block['kind'] ?? null) === 'table'
                ? $this->tableBlock($block)
                : $this->fieldsBlock($block);
        }

        return $out === ''
            ? '<h2>Contents</h2><p class="empty">No sections were included.</p>'
            : $out;
    }

    /** @param array<string, mixed> $block */
    private function fieldsBlock(array $block): string
    {
        $rows = [];
        foreach (($block['rows'] ?? []) as $row) {
            if (is_array($row)) {
                $rows[(string) ($row['label'] ?? '')] = $row['value'] ?? null;
            }
        }

        return $rows === []
            ? '<p class="empty">Nothing recorded.</p>'
            : $this->fieldTable($rows);
    }

    /** @param array<string, mixed> $block */
    private function tableBlock(array $block): string
    {
        $columns = array_values(array_filter(
            (array) ($block['columns'] ?? []),
            'is_scalar',
        ));
        $rows = (array) ($block['rows'] ?? []);

        if ($rows === []) {
            $message = $this->text($block['empty_message'] ?? 'Nothing recorded.');

            return '<p class="empty">'.$message.'</p>';
        }

        $head = '';
        foreach ($columns as $column) {
            $head .= '<th>'.$this->text($column).'</th>';
        }

        $body = '';
        foreach ($rows as $row) {
            if (! is_array($row)) {
                continue;
            }
            $body .= '<tr>';
            // Rows arrive as positional lists matching `columns`; padding keeps
            // a short row from silently shifting every cell after it.
            $cells = array_values($row);
            for ($i = 0; $i < max(count($columns), count($cells)); $i++) {
                $body .= '<td>'.$this->text($cells[$i] ?? '').'</td>';
            }
            $body .= '</tr>';
        }

        return "<table><thead><tr>{$head}</tr></thead><tbody>{$body}</tbody></table>";
    }

    /** @param array<string, mixed> $rows */
    private function fieldTable(array $rows): string
    {
        $out = '';
        foreach ($rows as $label => $value) {
            $shown = ($value === null || $value === '') ? 'Not recorded' : $value;
            $out .= '<tr><td>'.$this->text($label).'</td><td>'
                .$this->text($shown).'</td></tr>';
        }

        return '<table class="fields"><tbody>'.$out.'</tbody></table>';
    }

    private function banner(string $message): string
    {
        return '<p class="banner">'.$this->text($message).'</p>';
    }

    private function moment(mixed $iso): ?string
    {
        if (! is_string($iso) || $iso === '') {
            return null;
        }
        try {
            return \Carbon\Carbon::parse($iso)->format('j M Y, H:i');
        } catch (\Throwable) {
            return $iso;
        }
    }

    /**
     * Everything rendered here came from the patient's own record — free-text
     * notes, medication names, a recipient typed by staff — so every value is
     * escaped. A report is also mailed onward and opened outside the app.
     */
    private function text(mixed $value): string
    {
        if (is_bool($value)) {
            return $value ? 'Yes' : 'No';
        }
        if (is_array($value)) {
            $value = implode(', ', array_filter($value, 'is_scalar'));
        }

        return htmlspecialchars((string) ($value ?? ''), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
