/// Single source of route names so guards and navigators stay in sync.
///
/// Naming convention: `{role}{Feature}` for role-specific routes.
/// Shared routes have no prefix. All route strings start with `/`.
class RouteNames {
  RouteNames._();

  // ---------- Pre-login ----------------------------------------------------
  static const home = '/';
  static const landing = '/home';
  static const login = '/login';
  static const register = '/register';
  static const verifyEmail = '/verify-email';
  static const forgotPassword = '/forgot-password';
  static const resetPassword = '/reset-password';
  static const pendingApproval = '/pending-approval';

  /// Invite acceptance flow (clinicians/assistants/admins land here from
  /// the email link generated by an admin).
  static const acceptInvite = '/accept-invite';

  /// External-doctor token portal (`/external/:token`).
  static const externalDoctor = '/external';

  // ---------- Patient ------------------------------------------------------
  static const patientOnboarding = '/patient/onboarding';
  static const patientDashboard = '/patient';
  static const patientVitals = '/patient/vitals';
  static const patientVitalDetail = '/patient/vitals/detail';
  static const patientVitalHistory = '/patient/vitals/history';
  static const patientVital7Day = '/patient/vitals/week';
  static const patientMedications = '/patient/medications';
  static const patientMedicationDetail = '/patient/medications/detail';
  static const patientAppointments = '/patient/appointments';
  static const patientAppointmentDetail = '/patient/appointments/detail';
  static const patientDocuments = '/patient/documents';
  static const patientMessages = '/patient/messages';
  static const patientChatThread = '/patient/messages/thread';
  static const patientCareTeam = '/patient/care-team';
  static const patientNotifications = '/patient/notifications';
  static const patientProfile = '/patient/profile';
  static const patientForcePassword = '/patient/force-password';
  static const patientSettings = '/patient/settings';
  static const patientSupport = '/patient/support';
  static const patientTicketDetail = '/patient/support/detail';
  static const patientSos = '/patient/sos';

  // ---------- Doctor (§9.2) -----------------------------------------------
  static const doctorDashboard = '/doctor';
  static const doctorOverview = '/doctor/overview';
  static const doctorVitals = '/doctor/vitals';
  static const doctorVitalTemplate = '/doctor/vitals/template';
  static const doctorInbox = '/doctor/inbox';
  static const doctorAlerts = '/doctor/alerts';
  static const doctorAlertDetail = '/doctor/alerts/detail';
  static const doctorPatients = '/doctor/patients';
  static const doctorPatientChart = '/doctor/patients/chart';
  static const doctorVisits = '/doctor/visits';
  static const doctorAppointments = '/doctor/appointments';
  static const doctorPrescriptions = '/doctor/prescriptions';
  static const doctorReports = '/doctor/reports';
  static const doctorReportEditor = '/doctor/reports/editor';
  static const doctorMessages = '/doctor/messages';
  static const doctorChatThread = '/doctor/messages/thread';
  static const doctorNotifications = '/doctor/notifications';
  static const doctorProfile = '/doctor/profile';
  static const doctorCompleteProfile = '/doctor/complete-profile';
  static const doctorForcePassword = '/doctor/force-password';
  static const doctorSettings = '/doctor/settings';
  static const doctorSos = '/doctor/sos';

  // ---------- Admin (§9.3) ------------------------------------------------
  static const adminDashboard = '/admin';
  static const adminSos = '/admin/sos';
  static const adminPatients = '/admin/patients';
  static const adminUsers = '/admin/users';
  static const adminUserDetail = '/admin/users/detail';
  static const adminApprovals = '/admin/approvals';
  static const adminCareRequests = '/admin/care-requests';
  static const adminAssignments = '/admin/assignments';
  static const adminVitalCatalog = '/admin/vital-catalog';
  static const adminPermissions = '/admin/permissions';
  static const adminSupport = '/admin/support';
  static const adminAudit = '/admin/audit';
  static const adminAnalytics = '/admin/analytics';
  static const adminSystem = '/admin/system';
  static const adminMessages = '/admin/messages';
  static const adminChatThread = '/admin/messages/thread';
  static const adminNotifications = '/admin/notifications';
  static const adminProfile = '/admin/profile';
  static const adminSettings = '/admin/settings';
  static const adminCompleteProfile = '/admin/complete-profile';
  static const adminForcePassword = '/admin/force-password';
  static const adminAnnouncements = '/admin/announcements';
  static const adminSecurity = '/admin/security';
  static const adminAlerts = '/admin/alerts';

  // ---------- mCare Assistant (§9.4) --------------------------------------
  // Renders dynamically — items appear only when permission is granted.
  static const assistantDashboard = '/assistant';
  static const assistantPatients = '/assistant/patients';
  static const assistantApprovals = '/assistant/approvals';
  static const assistantCareRequests = '/assistant/care-requests';
  static const assistantAssignments = '/assistant/assignments';
  static const assistantUsers = '/assistant/users';
  static const assistantUserDetail = '/assistant/users/detail';
  static const assistantSupport = '/assistant/support';
  static const assistantAudit = '/assistant/audit';
  static const assistantAnalytics = '/assistant/analytics';
  static const assistantAlerts = '/assistant/alerts';
  static const assistantMessages = '/assistant/messages';
  static const assistantChatThread = '/assistant/messages/thread';
  static const assistantNotifications = '/assistant/notifications';
  static const assistantProfile = '/assistant/profile';
  static const assistantSettings = '/assistant/settings';
  static const assistantCompleteProfile = '/assistant/complete-profile';
  static const assistantForcePassword = '/assistant/force-password';
  static const assistantSos = '/assistant/sos';
  static const assistantVitalCatalog = '/assistant/vital-catalog';
  static const assistantAnnouncements = '/assistant/announcements';
  static const assistantSecurity = '/assistant/security';
}
